version: "3"

services:
  authentication_microservice:
    image: authentication_microservice
    container_name: authentication_microservice
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 3333
    ports:
      - 3333:3333
    env_file:
      - ./.env
